; Force Xdebug configuration with higher precedence
[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes
; Docker Desktop: use host.docker.internal to reach the IDE
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=VSCODE
xdebug.log=/tmp/xdebug.log
xdebug.log_level=7
